### ISSUE TITLE
Error Key

### ISSUE THREAD

**Issue by OverloadedTech** [hasherezade/petya_key#1]
Hello, i have a problem, i am trying on a VM Petya and this descriptor but using the decryption tool i can not find the decryption key why my key is not readable (see screenshot) what can i do? I checked the decryption code entered and i confirm that it is correct. How can i fix this
![InkedCattura](https://user-images.githubusercontent.com/68642373/175384868-58125ce0-c769-446a-8b52-6deb59278b2f.jpg)
?

**Comment by hasherezade** [comment]
Hi @OverloadedTech !
There are two possibilities why this could happen:
1) The victim ID is long, and it is very common that people make a typo in it, which causes invalid decryption. Please check in a good details if it is not just a typo. You can also send me the screenshot of your lockscreen, and I will help you and make sure that the data to the decryptor was passed in a valid format.
2) The Petya that is currently in the circulation is not the official version, and it is possible that it has been patched in a way that recovering the key with this tool is not possible - as it was made for the original Petya version.

**Comment by OverloadedTech** [comment]
Ok, thank you i will try and i will see what can i do?
